"""Regenerate the demo Spaces' example transcripts from the held-out eval set.

The transcripts themselves are NOT committed — they are ~200 KB of derived data that
already lives in `runs/<checkpoint>/eval/*_pairs.json`, and committing a second copy
invites the two drifting apart. Run this to rebuild before deploying either Space.

    python demo/make_examples.py --out-py  demo/space_gradio/examples.py
    python demo/make_examples.py --out-js  demo/space_wasm/examples.js

**Only short meetings.** Both demos run CPU inference (the Gradio Space is on ZeroGPU
hardware but loads with `n_gpu_layers=0`; the WASM one runs in the browser), so a
53-chunk transcript is not a demo — and long meetings are the model's known weakness
anyway, which the Space README says outright rather than hiding behind a curated pick.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from arcsum.chunker import CHUNK_TOKENS, iter_chunks  # noqa: E402
from arcsum.tokens import heuristic_token_len  # noqa: E402
from arcsum.transcript import parse_transcript  # noqa: E402

DEFAULT_PAIRS = REPO / "runs/sft-dropv2/g_agent_pairs.json"
DEFAULT_PICKS = [
    "KingCountyCC_04252016",
    "SeattleCityCouncil_01032017",
    "SeattleCityCouncil_09102018",
]

#: Extra transcripts committed under `demo/extra_examples/` rather than pulled from a
#: pairs file. These exist to show the model on material the eval set does NOT contain:
#: real ASR (not TranslateGemma-translated MeetingBank), a commercial rather than
#: municipal domain, and genuine recognition noise -- the opening lines of the DRAM
#: meeting are repeated subtitle boilerplate, which exercises the `NOP` path that every
#: MeetingBank-derived example leaves untouched.
#:
#: **Anonymised before commit.** The source was a real supply-chain negotiation; every
#: company, customer, vendor, person and identifying place name was replaced with a
#: fictive equivalent and the result audited against the original name list. Pricing and
#: negotiating positions were left intact because, with the parties anonymised, they no
#: longer identify anyone and they are what makes the transcript a realistic test.
EXTRA_DIR = REPO / "demo/extra_examples"
EXTRA_PICKS = ["dram_supply_meeting.v2.txt"]

HEADER_JS = """/* Real held-out zh-TW meetings from the evaluation set (TranslateGemma-translated
 * MeetingBank, format v2). Only the SHORT ones: in-browser CPU inference is slow, and
 * the model's known weakness is long meetings anyway.
 *
 * GENERATED by demo/make_examples.py -- do not edit by hand. */

export const EXAMPLES = """

HEADER_PY = '''"""Real held-out zh-TW meetings from the evaluation set (TranslateGemma-translated
MeetingBank, format v2). Only the SHORT ones: the Space runs CPU inference, and the
model's known weakness is long meetings anyway.

GENERATED by demo/make_examples.py -- do not edit by hand.
"""

EXAMPLES = '''


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--pairs", type=Path, default=DEFAULT_PAIRS)
    p.add_argument("--out-py", type=Path, default=None)
    p.add_argument("--out-js", type=Path, default=None)
    p.add_argument("--meetings", nargs="*", default=DEFAULT_PICKS)
    p.add_argument("--extras", nargs="*", default=EXTRA_PICKS,
                   help="filenames under demo/extra_examples/ to include")
    args = p.parse_args(argv)

    if not args.out_py and not args.out_js:
        p.error("give --out-py and/or --out-js")

    pairs = {x["meeting_id"]: x for x in json.loads(args.pairs.read_text(encoding="utf-8"))}
    missing = [m for m in args.meetings if m not in pairs]
    if missing:
        print(f"[make-examples] not in {args.pairs}: {missing}", file=sys.stderr)
        return 1

    examples = {}
    for name in args.extras:
        f = EXTRA_DIR / name
        if not f.is_file():
            print(f"[make-examples] missing extra: {f}", file=sys.stderr)
            return 1
        src = f.read_text(encoding="utf-8")
        n = len(list(iter_chunks(parse_transcript(src), budget=CHUNK_TOKENS,
                                 token_len=heuristic_token_len)))
        label = f.stem.replace(".v2", "").replace("_", " ")
        examples[f"{label} — real ASR ({n} chunks)"] = src
        print(f"[make-examples] {f.name}: {n} chunks, {len(src)} chars", file=sys.stderr)

    for mid in args.meetings:
        src = pairs[mid]["source"]
        n = len(
            list(
                iter_chunks(
                    parse_transcript(src), budget=CHUNK_TOKENS, token_len=heuristic_token_len
                )
            )
        )
        # The chunk count goes in the label: it is what determines how long the demo
        # takes, and it is the axis the model's weakness lives on.
        examples[f"{mid} ({n} chunks)"] = src
        print(f"[make-examples] {mid}: {n} chunks, {len(src)} chars", file=sys.stderr)

    if args.out_js:
        args.out_js.write_text(
            HEADER_JS + json.dumps(examples, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8"
        )
        print(f"[make-examples] wrote {args.out_js}", file=sys.stderr)
    if args.out_py:
        args.out_py.write_text(
            HEADER_PY + json.dumps(examples, ensure_ascii=False, indent=4) + "\n", encoding="utf-8"
        )
        print(f"[make-examples] wrote {args.out_py}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
